name: CI/CD Deploy to EC2 using Docker

on:
  push:
    branches: [ main, master ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build backend image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/employee-backend:latest backend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/employee-backend:latest

      # Build frontend image
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/employee-frontend:latest frontend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/employee-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      # Deploy to EC2
      - name: Deploy Latest Docker Images on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/app

            # Pull latest images
            docker compose pull

            # Restart app with new containers
            docker compose up -d --force-recreate

            docker image prune -f
          EOF
